# Generated by Django 5.1.2 on 2025-08-07 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asset', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Handover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ho_date', models.DateField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
                ('approved_by_hr_date', models.DateField(blank=True, null=True)),
                ('approved_by_it_date', models.DateField(blank=True, null=True)),
                ('approved_by_comment', models.TextField(blank=True, null=True)),
                ('approved_by_hr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='handover_approved_hr', to='staff.staff')),
                ('approved_by_it', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='handover_approved_it', to='staff.staff')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handover_asset', to='asset.asset')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handover_staff', to='staff.staff')),
            ],
        ),
        migrations.CreateModel(
            name='HandoverReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hr_date', models.DateField(auto_now_add=True)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('return_condition', models.CharField(choices=[('LPT', 'Laptop'), ('MOB', 'Mobile Phone'), ('PRT', 'Printer'), ('DSK', 'Desktop'), ('AIO', 'All In One'), ('TV', 'Television')], default='LPT', max_length=100)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handover_return_asset', to='asset.asset')),
                ('handover', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handover_return', to='handover.handover')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handover_return_staff', to='staff.staff')),
            ],
        ),
    ]
