# Generated by Django 5.1.2 on 2025-08-07 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=100)),
                ('specs', models.TextField(max_length=100)),
                ('category', models.CharField(choices=[('LPT', 'Laptop'), ('MOB', 'Mobile Phone'), ('PRT', 'Printer'), ('DSK', 'Desktop'), ('AIO', 'All In One'), ('TV', 'Television')], max_length=50)),
            ],
        ),
    ]
